@startuml Network diagram

nwdiag {
	network internet {
		firewall [address="dhcp"];
		color = "red"
	}

	network dmz {
		address = "192.168.10.0/24";
		firewall [address="192.168.10.1"];
		webserver [address="192.168.10.2"];
		vpnserver [address="192.168.10.3"];
		dbserver [address="192.168.10.4", shape = database];
		color = "yellow"
	}

	network internal {
		address = "192.168.12.0/24";

		firewall [address="192.168.12.1"];

		fileserver [address="192.168.12.2"]
		dbserver2 [address="192.168.12.3", shape = database]
		client1 [address="192.168.12.4"]
		client2 [address="192.168.12.5"]
		client3 [address="192.168.12.6"]
		color = "green"
	}

}

@enduml